# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JFCeY5KOQ4wfOKx2KZjgtRf_Szp061mq
"""

class GreenZoneIndex:
    def __init__(self, territory_name, territory_area, green_zones):
      self.territory_name = territory_name
      self.territory_area = territory_area
      self.green_zones = green_zones

    
    def calculate_green_index(self, green_index):

      self.green_index = sum(self.green_zones) / self.territory_area
      
      return round(green_index * 100)

territory_name = "Пушкин"
territory_area = 28676
green_zones = [302, 487, 420, 325, 471, 363, 404]

print(territory_name)
print(calculate_green_index)